### ISSUE TITLE
About TODO move to telegram app

### ISSUE THREAD

**Issue by Shuimo03** [grafana/oncall#1456]
Hi, thank you for opening an issue!

Here is a quick checklist:

- [ ] Is it about Cloud or Open Source OnCall?
- [ ] Add OnCall backend & frontend versions.
- [ ] Include labels starting with "part:". Like `part:alertflow` or `part:schedules`.
- [ ] Include labels like `bug` or `feature request`.
- [ ] If it's a bug, include logs.

Hi, I see an TODO move to telegram app that remove All telegram? Can I come and do this TODO? If there is no problem
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/22347407/223054038-edda3462-ac87-4115-a904-ddedd01c6b22.png">

engine/apps/user_management/models/user.py

**Comment by Matvey-Kuk** [comment]
Of course, feel free to take this.
