### ISSUE TITLE
Mobile Schedules v1

### ISSUE THREAD

**Issue by imtoori** [grafana/oncall#2265]
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/oncall/issues/2266
- [ ] https://github.com/grafana/oncall/issues/2267
- [ ] https://github.com/grafana/oncall/issues/2318
- [ ] https://github.com/grafana/oncall/issues/2268
- [ ] https://github.com/grafana/oncall/issues/2319
- [ ] https://github.com/grafana/oncall/issues/2510
```
