### ISSUE TITLE
implement shift swap on mobile

### ISSUE THREAD

**Issue by imtoori** [grafana/oncall#2592]
```[tasklist]
### Tasks
- [x] add ssr creation flow
- [x] visualize ssr in chronological view
- [ ] https://github.com/grafana/oncall/issues/2714
- [ ] mobile app: handle incoming shift swap notifications
- [ ] mobile app: toggle for incoming shift swap notifications
```

**Comment by joeyorlando** [comment]
@imtoori The available API for this is:

```
GET/POST /api/internal/v1/shift_swaps
GET/PUT/PATCH/DELETE /api/internal/v1/shift_swaps/<id>
POST /api/internal/v1/shift_swaps/<id>/take
```

Some things to note:
- you can't `PUT` or `PATCH` `beneficiary` or `benefactor`, you'll get back a 400. If you want to set the `benefactor` use the `/take` route.
- response schema:
  ```json
  {
        "id": <str>,
        "created_at": <datetime_str_in_utc>,
        "updated_at": <datetime_str_in_utc>,
        "schedule": <str>,
        "swap_start": <datetime_str_in_utc>,
        "swap_end": <datetime_str_in_utc>,
        "beneficiary": <str>,
        "status": <open|taken|past_due|deleted>,
        "benefactor": <str|None>,
        "description": <str|None>,
  }
  ```


These endpoints are already enabled in dev. **Note** if you're running it locally you'll need to set the following in your `./dev/.env.dev` file:
```env
FEATURE_SHIFT_SWAPS_ENABLED=True
```

**Comment by joeyorlando** [comment]
@maskin25
