### ISSUE TITLE
[Shift Swap Request] 🐛 Tracker

### ISSUE THREAD

**Issue by joeyorlando** [grafana/oncall#2857]
### What went wrong?

**What happened**:
-

**What did you expect to happen**:
-

### How do we reproduce it?

1. Open Grafana OnCall and do X
2. Now click button Y
3. Wait for the browser to crash. Error message says: "Error..."

### Grafana OnCall Version

v1.3.25

### Product Area

Schedules

### Grafana OnCall Platform?

None

**Comment by joeyorlando** [comment]
Moving [comment](https://github.com/grafana/oncall/issues/2844#issuecomment-1688033388) by @raphael-batte from #2844:

----

**Collection from 21/08 **
- [ ] highlight new swap request block in the calendar by yellow color
- [ ] disable renaming for the modal
- [ ] add swap requester name to the field in the modal
- [ ] 'Take' button is disabled for requester
- [ ] Add link button to open SSR in Slack

**- [ ] Naming**
Titles
1. Shift swap request - requested state
2. Shift swap - Accepted by user state
Users
3. Requested by
4. Swapped by
Buttons
5. Create
6. Accept
