### ISSUE TITLE
Make SSRs on mobile more discoverable

### ISSUE THREAD

**Issue by imtoori** [grafana/oncall#3035]
```[tasklist]
### Tasks
- [ ] Check stats on current SSR discoverability (number of ssrs and user flow)
- [ ] Test a simple highlight for ssr button and evaluate the impact
- [ ] Add a ssr button to the personal schedule page (shifts)
```
