### ISSUE TITLE
Mobile multistack backend support

### ISSUE THREAD

**Issue by imtoori** [grafana/oncall#3452]
for the multistack project we need a couple of things from the backend 

Milestone: https://github.com/grafana/oncall-private/issues/2072

```[tasklist]
### Tasks
- [x] Let the django_fcm library allow tokens to belong to multiple users
- [x] Provide stack slug in the authentication response
- [x] Add slug to notifications data payload
- [x] Add slug to notification title
```
